name: CVChat
main: org.cubeville.cvchat.CVChat
authors: [FrediW,ToeMan_]
version: 1.20
depend: [CVIPC,CVTools,CVVanish]
api-version: 1.18

commands:
  modreq:
    description: Send moderator request
  unlocktutorialchat:
    description: Unlocks tutorial chat
  finishtutorial:
    description: Finishes tutorial
  ltr:
    description: Fake local chat
    permission: cvchat.fakelocal
  localchatregion:
    description: Local chat region administration
    permission: cvchat.localchatregion
  localchatworld:
    description: Local chat world administration
    permission: cvchat.localchatworld
  localchardistance:
    permission: cvchat.localchatdistance
    description: Change local chat default distance temporarily
  locchat:
    permissions: cvchat.locchat
    description: Toggle